language: scala
scala:
  - 2.11.1
jdk:
  - oraclejdk8
script: "sbt ++$TRAVIS_SCALA_VERSION stage full-test"
after_success: "sbt ++$TRAVIS_SCALA_VERSION stage deployHeroku"
env:
  global:
    secure: xEyenAGjq6yZqCQeeN/F59UWvnczXzoBYge9EFSkZ2roonFjrB4gCdXUqLfnwPg/h5SbXm3Y/xB+5aO1yikMzQfqgthApw4FV10/TcjG8bbWOc7j3zr8Mq8iv2MOiQ1iKkx5MXeLtAG/ekKItJ+7Yd1sykkbXipEcQ0MkHd7aZNNn9VAYsgsdgeEpFbpaCooAqEiLv4uUSfUPReHtpaH0pB7h+OGjFoH4MpRx0OsVxc4as7+VI3Q50OBHCT2rp/2o9Zlj95Jf2+NzfSo+D1tmPSDQmtpk3Dp/ncuJZGP94c9SvS1FgQcPluwUK4gcpTfLR/B6d+ZEUGvPZw0lpn3gwKrMS5Lpf0Jx95WzQ3V+NgApXpHZlB+oYrF4b39EZ28Dzg7nWl3SteQFfJ8fvCdg8ZsJTMTRePxi7ber+xsJSpmJ+UEmKjuMwq+Sa9dKR04ge12ha3I7xL1+vpbjD49vhCHRcIqqHJTA5S3/FUscb1L7MDUiRBM2QWzvDKWM4T1IR4Eko3MmFxzJv3kHo3WNfpFUxxGJJ3T/ogUFFDFVaxJbGEOjzNVDba4AcfASWfZKRIERO6bZq0ryCqHUKWe+eH9p9zOaBI4MmAn4/IXcwI6CELdfua2XvHdbhenUoM33j12Ka3cw/AxTSf3KBA2jbWSeam2xaRPnfIwPTTwJWQ=
